name: Power Platform Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  POWER_PLATFORM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  POWER_PLATFORM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  POWER_PLATFORM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  TARGET_DIR: ${{ github.workspace }}

jobs:
  terraform:
    name: 'Deploy Power Platform Resources'
    runs-on: ubuntu-latest
  

    steps:
    - name: Debug
      uses: raven-actions/debug@v1
      with:
        vars-context: ${{ toJson(vars) }}  # optional
        secrets-context: ${{ toJson(secrets) }}  # optional
        needs-context: ${{ toJson(needs) }}  # optional
        inputs-context: ${{ toJson(inputs) }}  # optional

    - name: 'Checkout repository'
      uses: actions/checkout@v3

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8
 

    - name: 'Initialize Terraform'
      run: terraform init

    - name: 'Validate Terraform'
      run: terraform validate

    - name: 'Plan Terraform'
      id: tf-plan
      env:
       POWER_PLATFORM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
       POWER_PLATFORM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       POWER_PLATFORM_CLIENT_SECRET: ${{ secrets.AZURE_TENANT_ID }}
       TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
       TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
       TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        export exitcode=0
        terraform -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" -chdir=$TARGET_DIR plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?

        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        
        if [ $exitcode -eq 1 ]; then
          echo Terraform Plan Failed!
          exit 1
        else 
          exit 0
        fi

    - name: 'Apply Terraform'
      if: github.ref == 'refs/heads/main'
      run: terraform apply tfplan
