name: Power Platform Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  POWER_PLATFORM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  POWER_PLATFORM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  POWER_PLATFORM_CLIENT_SECRET: ${{ secrets.AZURE_TENANT_ID }}


jobs:
  terraform:
    name: 'Deploy Power Platform Resources'
    runs-on: ubuntu-latest
  

    steps:
    - name: Debug
      uses: raven-actions/debug@v1
      with:
        vars-context: ${{ toJson(vars) }}  # optional
        secrets-context: ${{ toJson(secrets) }}  # optional
        needs-context: ${{ toJson(needs) }}  # optional
        inputs-context: ${{ toJson(inputs) }}  # optional

    - name: 'Checkout repository'
      uses: actions/checkout@v3

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8
 

    - name: 'Initialize Terraform'
      env:
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      run: terraform init

    - name: 'Validate Terraform'
      env:
       POWER_PLATFORM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
       POWER_PLATFORM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       POWER_PLATFORM_CLIENT_SECRET: ${{ secrets.AZURE_TENANT_ID }}
      run: terraform validate

    - name: 'Plan Terraform'
      env:
       POWER_PLATFORM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
       POWER_PLATFORM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       POWER_PLATFORM_CLIENT_SECRET: ${{ secrets.AZURE_TENANT_ID }}
       TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
       TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
       TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      run: terraform plan -out=tfplan

    - name: 'Apply Terraform'
      if: github.ref == 'refs/heads/main'
      env:
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      run: terraform apply tfplan
